### PR TITLE
Added: postcss-image-set-polyfill (#43)

### PR DESCRIPTION
**Pull request by SuperOl3g**
Solves #43

### CODE REVIEW

**Comment by SuperOl3g** [comment]
Aaauch... not working with ES6, will fix it tomorrow

But some tests also isn't passed in original repo
```
not ok 95 should add autoprefixer support
  ---
    operator: equal
    expected: |-
      '* {\n  -webkit-transition: -webkit-transform 1s;\n  transition: -webkit-transform 1s;\n  transition: transform 1s;\n  transition: transform 1s, -webkit-transform 1s;\n}\n\n@-webkit-keyframes spin {\n  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }\n  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }\n}\n\n@keyframes spin {\n  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }\n  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }\n}'
    actual: |-
      '* {\n  transition: -webkit-transform 1s;\n  transition: transform 1s;\n  transition: transform 1s, -webkit-transform 1s;\n}\n\n@-webkit-keyframes spin {\n  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }\n  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }\n}\n\n@keyframes spin {\n  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg) }\n  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg) }\n}'
    at: testFeature (/home/travis/build/MoOx/postcss-cssnext/lib/__tests__/option.features.js:41:5)
```

**Comment by MoOx** [comment]
Some tests are probably out of date. Feel free to make a PR to fix those :)

**Comment by Semigradsky** [comment]
This error happens because `browserslist` defaults is dynamic. We should pass `browsers` option in tests.

**Comment by Semigradsky** [comment]
I have fixed it in 2ca6df019e76404d0fd40ffd37190efce08f8392

**Comment by Semigradsky** [comment]
@MoOx how about publish new version?
https://github.com/MoOx/postcss-cssnext/milestones/v2.11.0

**Comment by MoOx** [comment]
Yeah why not. Do you want me to cut a release from master? Not sure why you created a milestone with an issue that's look fixed in master.

**Comment by Semigradsky** [comment]
I just forgot to close issue.

**Pull request merged**
