### PR TITLE
Move `chalk` to deps

### LINKED ISSUE #265: Move `chalk` from `devDependencies` to `dependencies`
It is used in the main library: https://github.com/MoOx/postcss-cssnext/blob/master/src/warn-for-duplicates.js#L2

This is critical, everything fails because `chalk` can't be required.

### PR DESCRIPTION
**Pull request by s-panferov**
Fixes #265

### CODE REVIEW

**Comment by keithamus** [comment]
LGTM. Looks like `2.5.0` introduced this failure because, as @s-panferov says in #265, warn-for-duplicates uses chalk.

**Comment by gcedo** [comment]
:+1: would be [awesome possum](https://www.youtube.com/watch?v=V5Z_ZducwbQ) to have this merged soon :blush:

**Comment by MoOx** [comment]
Oups, sorry guys :D

**Comment by keithamus** [comment]
Thanks @MoOx you're the best :+1: Keep up the great work

**Comment by MoOx** [comment]
Released as 2.5.1

**Comment by gcedo** [comment]
Thanks @MoOx, super cool!

**Pull request merged**
