### PR TITLE
Upgrade postcss-apply dependency

### PR DESCRIPTION
**Pull request by pascalduez**
- Implement proper property set overrides
- See https://github.com/pascalduez/postcss-apply/issues/10

### CODE REVIEW

**Comment by MoOx** [comment]
Can I release this as a patch? Looks like it's a patch.

**Comment by pascalduez** [comment]
> Can I release this as a patch? Looks like it's a patch.

I would say so. 
Except if people where relying on the erroneous previous behavior.

**Comment by MoOx** [comment]
Can you provide an example of the change? Like input before+output and input after+output?

**Comment by pascalduez** [comment]
### input
```css
:root {
  --foobar: {
    color: red;
    content: 'foobar';
  };
}

.foo {
  @apply --foobar;
}

:root {
  --foobar: {
    color: blue;
  };
}

.bar {
  @apply --foobar;
}
```

### Before

output
```css
.foo {
  color: red;
  content: 'foobar';
}

.bar {
  color: blue;
}
```

### After

output
```css
.foo {
  color: blue;
}

.bar {
  color: blue;
}
```

**Comment by MoOx** [comment]
Ok thanks. This will cause trouble for sure. Will cut a major release for this.

**Comment by ritasousa-farfetch** [comment]
Would it be possible to update to v0.6 of postcss-apply instead of just v0.4?

**Comment by pascalduez** [comment]
Bumped the version, updated the commit message. 
Please see the [Changelog](https://github.com/pascalduez/postcss-apply/blob/master/CHANGELOG.md) for differences.

There's still something I would like to work out and will then release a `1.0.0` though.

**Comment by MoOx** [comment]
Closing in favor of #400

**Pull request closed without merging**
