### PR TITLE
Added osx support to travis ci

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by MoOx** [comment]
Hi, thanks for your PR. Was is the real value behind this since osx is unix based like "linux"?

**Comment by amilajack** [comment]
In some cases there is. Usually when libs have dependencies with native bindings, guaranteeing their functionality across multiple platforms can be difficult.

**Comment by amilajack** [comment]
But most of the time this isnt a problem.

**Comment by MoOx** [comment]
Thanks, I will pass on this since for now there is no know issues related to osx. As soon as we will have some, I will reconsider this.

**Pull request closed without merging**
