### PR TITLE
tests: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.

https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

### CODE REVIEW

**Comment by jonathantneal** [comment]
@DanielRuf, thanks for submitting this improvement to plugins! Did you see speed improvements in this iteration?

**Comment by DanielRuf** [comment]
current
https://travis-ci.org/MoOx/postcss-cssnext/builds/331688424?utm_source=github_status&utm_medium=notification

with npm ci
https://travis-ci.org/MoOx/postcss-cssnext/builds/369190700?utm_source=github_status&utm_medium=notification

So yes, there is a significant improvement.

**Comment by jonathantneal** [comment]
@DanielRuf, I always appreciate your extra help. Thanks 😄

**Comment by DanielRuf** [comment]
You mean Node.js 4? Node.js 4 does not support many of the current Node.js structures (especially  lock scoped declarations which is needed for the new npm and other dependencies) .

Node.js 4 is EOL since this week and relying on it is mostly not possible anymore as many deps require 6+ (for example puppeteer and others).

We can also try to create a matrix and run the normal `npm i` on Node.js 4.

**Comment by DanielRuf** [comment]
See #460 and https://travis-ci.org/MoOx/postcss-cssnext/jobs/374177551#L443

**Comment by DanielRuf** [comment]
Not yet 100% sure why it was working in the PR but it should not have on Node.js 4 due to the needed features.

**Comment by DanielRuf** [comment]
But Node.js 4 is and was already failing (on Windows), see https://ci.appveyor.com/project/MoOx/postcss-cssnext/build/132

**Comment by DanielRuf** [comment]
https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742

https://github.com/nodejs/Release

**Comment by jonathantneal** [comment]
@DanielRuf, thank you for sharing, and I agree with your conclusions. If there is to be another cssnext release, perhaps it should drop Node 4 (or at least Node 4 testing). If it kept Node 4 compilation, this would be only be to align with the present PostCSS release.

**Pull request merged**
