### PR TITLE
Postcss6 upgrade

### LINKED ISSUE #374: Upgrade to postcss 6.x
This requires a major version bump.

[PostCSS Changelog](https://github.com/postcss/postcss/blob/master/CHANGELOG.md#60-marquis-orias)

### LINKED ISSUE #389: Bug with nesting
Hi, I found strange bug that I cannot reproduce in playground.
I have following `foo.css`:
```css
.foo {
    color: #000;
    &__bar {
        color: #aaa;
    }

    &__baz {
        color: #bbb;

        &:hover {
            color: #ccc;
        }
    }
}

```
And next `gulpfile.js`:
```js
const gulp = require("gulp");
const postcss = require("gulp-postcss");

gulp.task('css', function () {
    return gulp.src('foo.css')
        .pipe( postcss([ require('postcss-cssnext') ]) )
        .pipe( gulp.dest('build/') );
});

```
`package.json`:
```json
{
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-postcss": "^7.0.0",
    "postcss-cssnext": "^2.11.0"
  }
}
```
I expect:
```css
.foo {
    color: #000
}
.foo__bar {
    color: #aaa
}
.foo__baz {
    color: #bbb
}
.foo__baz:hover {
    color: #ccc
}
```
But I found:
```css
.foo__baz {
        color: #bbb;

        &:hover {
            color: #ccc;
        }
}.foo {
    color: #000
}

.foo__bar {
        color: #aaa;
}

```

What am I doing wrong?
Can you please help me with the right setup?
Thanks!

### PR DESCRIPTION
**Pull request by MoOx**
Closes #384 
Closes #374 
Closes #389

### CODE REVIEW

**Comment by MoOx** [comment]
Maybe we can cut a release with this as v3 and plan a v4?

**Comment by shouze** [comment]
@MoOx yup... and do you plan to sill support node 0.12?

**Comment by MoOx** [comment]
It depends on deps support. So I think it will be node6+

**Comment by MoOx** [comment]
Only 0.12 is not passing, so node4+ should do it.

**Comment by Spy-Seth** [comment]
A agree as node 4 is still in LTS 👍

**Pull request merged**
