### PR TITLE
Internal: pleeease-filters@3.0.0

### PR DESCRIPTION
**Pull request by nulltask**
3.0.0 changelog is here: https://github.com/iamvdo/pleeease-filters/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by MoOx** [comment]
Can this be considered as a patch?

**Comment by nulltask** [comment]
Yes.

Should I change to branch name to better?

**Comment by MoOx** [comment]
No problem ;)

**Comment by nulltask** [comment]
Thanks :)

**Pull request merged**
