### PR TITLE
postcss-custom-properties version fix to 6.2.0

### PR DESCRIPTION
**Pull request by japboy**
hotfix

### CODE REVIEW

**Comment by japboy** [comment]
oops i made wrong pr. closing now.

**Comment by MoOx** [comment]
Thanks but it's totally unecessary. You can just uninstall and reinstall cssnext and you will get this change ;)

**Comment by japboy** [comment]
fyi, postcss-custom-properties 6.3.0 which is released today changed its own default behaviour disabling transpiling custom properties into hard-coded values, and it sucks my day. anyway sorry for wrong pr.

**Comment by jonathantneal** [comment]
^ disabling transpiling custom properties into hard-coded values

That is not accurate. The original `var()` rules are preserved. Browsers not supporting variables should not experience a change.

**Comment by jonathantneal** [comment]
@japboy, a patch version 6.3.1 has been released that reverts the changes to these options, which are being restored in 7.0.0. I’d like to know more about what CSS was breaking for you, because I’m left to suspect you have some non-spec-compliant Custom Properties usage going on.

**Pull request closed without merging**
