### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by coderhaoxin**

### CODE REVIEW

**Comment by MoOx** [comment]
The tests are failing now https://travis-ci.org/MoOx/postcss-cssnext/jobs/181888295#L1001

Can you take a look to the change and adjust the tests accordingly please?

**Comment by coderhaoxin** [comment]
submit a PR to fix the broken!

https://github.com/jonathantneal/postcss-pseudo-class-any-link/pull/6

**Comment by jonathantneal** [comment]
@coderhaoxin, that was resolved in any-link. You may want to resubmit your request or ask @MoOx to re-run the tests.

**Comment by coderhaoxin** [comment]
😢 `postcss-pseudo-class-any-link` needs `node@6+`.

**Comment by jonathantneal** [comment]
@coderhaoxin, I’m sorry that makes you sad. Would you be able to tell me why that is?

FWIW, the current LTS for Node has been [v6.9.2](https://nodejs.org/en/), and the older widely-used release (v0.12) ended support 8 months ago, with the last maintenance on it is scheduled to finish in 2 weeks ([cite](https://github.com/nodejs/LTS#lts-schedule)). All 20+ of my PostCSS plugins now require Node v6+. It has greatly improved their readability and maintainability.

**Comment by coderhaoxin** [comment]
I use node@6+, but `postcss-cssnext` needs support `0.12, 4, 5, 6` (according to `travis.yml`).

I'm +1 for dropping `0.12, 4, 5`.

**Comment by MoOx** [comment]
Will drop in v3....

**Comment by chris-morgan** [comment]
postcss-pseudo-class-any-link has gone back down to `node>=4`.

It would be a really bad idea to drop support for Node 4 here; quite apart from Node holding 4 under LTS for another year, Ubuntu, which is probably the most popular OS for users of cssnext (or at least close to it), [doesn’t have anything newer than Node 4 in its package manager at present](http://packages.ubuntu.com/search?keywords=nodejs).

**Comment by jonathantneal** [comment]
@chris-morgan, agreed. I am bumping the dependency down in all of my plugins and have not raised it in any of my PRs to this project.

**Comment by coderhaoxin** [comment]
updated :)

**Comment by MoOx** [comment]
Closing in favor of #400

**Pull request closed without merging**
